
language: csharp
dotnet: 2.0.2
mono: none

git:
  depth: 1000

os:
  - linux
  - osx
sudo: required
dist: trusty
osx_image: xcode8.1

matrix:
  fast_finish: true


addons:
  artifacts:
    paths: $(ls ./../PowerShellGet.zip | tr "\n" ":")


install:
  # Default 2.0.0 Ruby is buggy
  # Default bundler version is buggy
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      rvm install ruby-2.3.3;
      rvm --default use 2.3.3;
    fi
  - bash <(wget -O - https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.sh)
  - pushd tools
  - chmod +x travis.sh  
  - popd

script: 
  - echo "TRAVIS_EVENT_TYPE value $TRAVIS_EVENT_TYPE"
  - ./tools/travis.sh










