@{
ModuleVersion="1.0.1.5"
GUID = '9b43ea9f-d25a-4342-b4ea-60dd018c6358'
Author="manikb"
CompanyName="Microsoft Corporation"
Copyright="© Microsoft Corporation. All rights reserved."
Description = 'Test module'
NestedModules="TestArchiveModule.psm1"
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
PrivateData = @{
    PSData = @{
        Tags = 'DifferentAuthenticodeIssuer'
    }
}
}

# SIG # Begin signature block
# MIIF0wYJKoZIhvcNAQcCoIIFxDCCBcACAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUvmB/p7EWrTgEM7JUUJ2E1PsI
# eMOgggNcMIIDWDCCAkCgAwIBAgIQNaQMCphAKYtOZhFDwzwauDANBgkqhkiG9w0B
# AQsFADAsMSowKAYDVQQDDCFQb3dlclNoZWxsR2V0IFRlc3QgUm9vdCBBdXRob3Jp
# dHkwHhcNMTYwODE5MDAwNTI3WhcNMTcwODE5MDAxNTI3WjAtMSswKQYDVQQDDCJQ
# b3dlclNoZWxsR2V0IENhdGFsb2cgQ29kZSBTaWduaW5nMIIBIjANBgkqhkiG9w0B
# AQEFAAOCAQ8AMIIBCgKCAQEAi/5HjFYlGRxJlVbZFSK8AzByRoGQjnsVErwxdvf6
# qPG7vfCyS4bjkNq/5xBKL/wHCX5oePk9Ady4o6Kwq6Apw3UfY144UBxbxNFxMm/T
# /0nwPAf8cCAiorSQ930KLfGhdBiXLnguOgpyymFuqouc7wpF/FI2UTqqLhqgl6Mr
# ePKjDXkkEHR5g9bxZ7hJHqbBR6uOqVkiE0jbSrUogLOhCy7LAIw7C6W5e94DuL3x
# nBOCcB12bZs9BQKQJbw7JTkpggbTFERoHZq8PUf70V17Jb/y5poYN2q1V9vSaMm+
# iRZPFuTO7nRIcan3VeUjJnI7+EzxrzSNUuQGL1QCPqGNqQIDAQABo3UwczAOBgNV
# HQ8BAf8EBAMCAYYwDAYDVR0TAQH/BAIwADATBgNVHSUEDDAKBggrBgEFBQcDAzAf
# BgNVHSMEGDAWgBR26d63giiAxVPzIk1nEO6bzSKqNzAdBgNVHQ4EFgQU0+W7BfiE
# UgU8f3IK6cNp8J3DlbMwDQYJKoZIhvcNAQELBQADggEBABdnxgdQABbHL1kjAlqz
# aKyxsYGu+I5EoGE0xvp8P/abnsQTi2FdEX3ORFY16kjKUqlrS0U9n+UuVkW1R980
# ktvWuEQxYjloLRfgL3fXg/eKYBS8ScE9wZwrGq9n8cbXDRGZQMKQryslzfcZs7Lp
# rlR0mbIWfKWzjDNnLRFX+3xkjY2pIBjhYlsYPZkV9t8QsZF9IAqZxxVJicVsEOcA
# CJm9Zoz4IB7gdVjkbgRU69kmRLNen8Vv+fWsMrOuq6H1EpYY/ZVMl/GKHzuoRgus
# T6VljOUHkOKZQSZ/WwbWReLDwJ1awjhd1CedMbTx9bKjT+xniRMKEqCZV1uSvhhQ
# 3WAxggHhMIIB3QIBATBAMCwxKjAoBgNVBAMMIVBvd2VyU2hlbGxHZXQgVGVzdCBS
# b290IEF1dGhvcml0eQIQNaQMCphAKYtOZhFDwzwauDAJBgUrDgMCGgUAoHgwGAYK
# KwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIB
# BDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQU
# XPqJGpc/7qZx512BnZd4wBJ4AWwwDQYJKoZIhvcNAQEBBQAEggEATVPNUC8Oft4O
# eVTgpeQBqQjrO7ZADFPgB94CZuYtQFjBUGd2JI/tc+/8e4DuWj+vqy2p+UJs9cif
# rBDQtaQL9gWI1FfIUM6dTxHHFjRVVSsMtP/LZNQAlnsvHz9Hj6f8RgzTTVDJwjLi
# vtq2WitywvbPtR0JHxKW+HLsMpKQBeUpNHniui+0Xtj24nrTSVrb4KjtBGeltymX
# n7ddsibmLU5QeUeuSY8kk5X+jE52Ehs7KzYXSBkOLkAFLDxfJrQuaYJ0VJXjVwvo
# /PZsbMdQDzRvfBXPwMrpz4K3x/oDAIsjaYT71SDwKAK7kBuVFngLWrIX00Q6sqBC
# q/iUDRvM1w==
# SIG # End signature block
