@{
ModuleVersion="1.0.1.11"
GUID = '9b43ea9f-d25a-4342-b4ea-60dd018c6358'
Author="manikb"
CompanyName="Microsoft Corporation"
Copyright="© Microsoft Corporation. All rights reserved."
Description = 'Test module'
NestedModules="TestArchiveModule.psm1"
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
PrivateData = @{
    PSData = @{
        Tags = 'ValidCatalogSignedLatest'
    }
}
}

# SIG # Begin signature block
# MIIFvwYJKoZIhvcNAQcCoIIFsDCCBawCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU5NaxYJvgpMEAZsFIty7dEiAK
# eiOgggNMMIIDSDCCAjCgAwIBAgIQTpO3RNGnQ6hFc1a6Iu66bTANBgkqhkiG9w0B
# AQsFADAoMSYwJAYDVQQDDB1QU0NhdGFsb2cgVGVzdCBSb290IEF1dGhvcml0eTAe
# Fw0xNjA4MTkwMDA1MDJaFw0xNzA4MTkwMDE1MDJaMCExHzAdBgNVBAMMFlBTQ2F0
# YWxvZyBDb2RlIFNpZ25pbmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDzDpS+berD3W9xRi0Poxhi1CKNFSom6yPoB9iKWeFJeiZOk4Tl5KZvyJdg0a/V
# Rj2ptlpLM8JpgXa++ce0JYPD7qRRHDEGqpbCZOTogu8kvydMVE5y3iSXIi5KYpVh
# 4Ofl7pI/e61KRGU7DTUMGVLatLOI7bBH0HnxFBR7HuTt5BUGWawSw4FGZVp/UiNT
# M1RTaj3HYIUar5GdznO3J1lyoT0aMDHHwmC+MJxwXdIZcE7XDRyTFZPAxCwNOpI4
# vvUxPBNA3S4HmUdYiA5gSmvvzf1d4QYB/QQbfiMFxzaQXs0PNofUyrbGTh3TteHI
# 1uhktqj2Gx+nwr3Nc7xqZD8dAgMBAAGjdTBzMA4GA1UdDwEB/wQEAwIBhjAMBgNV
# HRMBAf8EAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMB8GA1UdIwQYMBaAFKQulF/P
# jZ0Z9uOeoDCCdTGjf/wsMB0GA1UdDgQWBBSz3QAk9Tn3cJvAwGRR19qgUTb0lDAN
# BgkqhkiG9w0BAQsFAAOCAQEAAMLgDq51LxkTEk/ObH0DjVa1Vz24yVxQYYhP5fPW
# DR7aDBvWSkPlVG0RHQ+Vhnjuahu7tGs3ZWKUfruR7ZkBfNPwFbjYxLnwpGrzQPXO
# GaHOmH2B8UcRr2H9tnu/F6N/jsVX4sK+QdXdmUgLNan9LKeeabNHdLh7OMuNm56T
# yS6C+h1Oop7CWSHy/5D1o+OzGETqJQ6vZ/X8694RGGpJ9bDRfhB+DHnzbV02bG+O
# ZHCzhz+b/5R8WvTI9W4JA0AeAZZBCa5GMbK6LvqbsKKsEpMJirBRPDu8k6bsvthz
# 4AkTYQWki1U5nkDLPJzQbGb5jr0n96k9NS8QpVp5y/xZlzGCAd0wggHZAgEBMDww
# KDEmMCQGA1UEAwwdUFNDYXRhbG9nIFRlc3QgUm9vdCBBdXRob3JpdHkCEE6Tt0TR
# p0OoRXNWuiLuum0wCQYFKw4DAhoFAKB4MBgGCisGAQQBgjcCAQwxCjAIoAKAAKEC
# gAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwG
# CisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYEFG6uHsBB31pugSxLMvLiFYoOiS0i
# MA0GCSqGSIb3DQEBAQUABIIBAATqbq5Fecq4XVsZK3DSBVPw4UM26iIMFXS0Z6ME
# tA5hFsHPsMhihias0jbZBvltsstHio7p0hedvVJGYtMFS7gEfrH3sYXWxU5r0rRW
# OjAotqnXenD7ax7JO1jZ8HZ6ioHZEfbswcrHSmTsmzcEpZZYsNnhrNqqFryS+hvj
# a0TSLNunnFqHaZyYemmJqoleXm8ycTGFX8T25KcQo+dMHLc2H8gxCLKUKX59syrG
# R0hXnrTX8KHcZ27r2pg68DAL9n0H9iNi8wnqir3rjujrnAFAni+OjF+t+bKqySl/
# 70R5ACr+ZqgzCWSR3PCRCjx/YVegqtdvAcv3Kk6xSIlljTo=
# SIG # End signature block
