@{
ModuleVersion="1.0.1.1"
GUID = '9b43ea9f-d25a-4342-b4ea-60dd018c6358'
Author="manikb"
CompanyName="Microsoft Corporation"
Copyright="© Microsoft Corporation. All rights reserved."
Description = 'Test module'
NestedModules="TestArchiveModule.psm1"
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
PrivateData = @{
    PSData = @{
        Tags = 'SystemModule', 'DifferentScopeModule', 'CatalogSignedModule'
    }
}
}

# SIG # Begin signature block
# MIIFvwYJKoZIhvcNAQcCoIIFsDCCBawCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUGvhWPbSwHzC6imsIJvSv5v5q
# J0CgggNMMIIDSDCCAjCgAwIBAgIQQl2njHG7xqpO6UUULKsJ1jANBgkqhkiG9w0B
# AQsFADAoMSYwJAYDVQQDDB1QU0NhdGFsb2cgVGVzdCBSb290IEF1dGhvcml0eTAe
# Fw0xNjA1MjQwMTI5MzlaFw0xNzA1MjQwMTM5MzhaMCExHzAdBgNVBAMMFlBTQ2F0
# YWxvZyBDb2RlIFNpZ25pbmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDSBiXVCByE7JuX+EJ8/BoNxU8XtU/exIaVkXy4ww6b/YIDP0gblYumn+2Clj6o
# PXhv1GW+y5mzw9aP0vtCDaT1+NR5aj9hV6Cq8j3P9f9awJC9S5QlJUNCGhcQn2FY
# KLS3NbznJ4TF8Vnd8BlM5EhtfL8kBYrbuShlRaA8p1aLcUw5VZTE3/45ZiXDNzAu
# OiudxoEko/0xWuyy3GJbdPRowX2Od6TSL/3iaF1sls6y1aBt86/3JuIcZnN5SmP4
# 9V4zmgQGzUi+AX+OpqTjyfj2JZQ54GsarTN2dQT4ClaCCz3tJSBAM7OFRD0kLCHR
# +tla3uzWOjglFdgCsah4+NSDAgMBAAGjdTBzMA4GA1UdDwEB/wQEAwIBhjAMBgNV
# HRMBAf8EAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMB8GA1UdIwQYMBaAFJVytkAT
# haUY7ODVlcWCRLmbBcelMB0GA1UdDgQWBBQPODajeho8+4YFG5ZSBYtO+kI7RjAN
# BgkqhkiG9w0BAQsFAAOCAQEAdrabTKhuCGbcmoOV84F9Q+gATJNHgWdlOvXmPUmy
# 0g3tJiHuChLdMPMvSV/ytXGfYcpuS/tmMMMYLhIs767kY2S8m6o0QJm/RzhiyD7S
# 3Pg4jrPFjciE1Q24+g2iXSvRZ2SKThLKN4k82oe92Gh5uDcLD9LyxaMv3YdXEj3M
# gfpwMeAIxPbmwnWIzoGgpE3XdCVqK/Z8MuX1GQ4zhOAWQkrQJRnxuH3BMsQsDxqS
# Rs4MIMKOf41Oq+EQnWxBUpL6rKQi1Dh1dfxfg9ZpkEk4LJYbr7Ej5k4mbFVn/bL5
# xFXispZ6wuJceWPzeN83UUC5KXjIgPiJ9ZRCXiJuWh72+zGCAd0wggHZAgEBMDww
# KDEmMCQGA1UEAwwdUFNDYXRhbG9nIFRlc3QgUm9vdCBBdXRob3JpdHkCEEJdp4xx
# u8aqTulFFCyrCdYwCQYFKw4DAhoFAKB4MBgGCisGAQQBgjcCAQwxCjAIoAKAAKEC
# gAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwG
# CisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYEFJ6LQ4vb7PDgx/cePy/OoO5l0xNl
# MA0GCSqGSIb3DQEBAQUABIIBAKb9wCBRRx5LfELhD9gecMVQFRDLLi2OH9R8I1Ye
# JgjMCVixaJVF6e4TIFtn0RqJyNliUh1pw0UsDT6YfOPsyhsFioWTiiu66QxVDQiz
# nEO85oLcPdrrm2SaTheZVS3MKXSkqTmzvVM5meT+PkWIrEdOfDvd2+uQTgtkAvsa
# Ncr5JzVeULyB1PKO+e9BgLcKlVZOcNTVU1X4Hwj2+j0uLZbpSvZ4dzCWjYSaNmWQ
# UNc6Gd5Y+ogiDWJi621nUp2PqNi1HKtUiV9NE7zTkfTm8b4NMC9nFZO4On5+l4s8
# e3nt4aUNJczDOzsuRV/q0LLbDXTl5VI0JZxnQuYTPvFK2XY=
# SIG # End signature block
