@{
ModuleVersion="1.0.1.1"
GUID = '9b43ea9f-d25a-4342-b4ea-60dd018c6358'
Author="manikb"
CompanyName="Microsoft Corporation"
Copyright="© Microsoft Corporation. All rights reserved."
Description = 'Test module'
NestedModules="TestArchiveModule.psm1"
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
PrivateData = @{
    PSData = @{
        Tags = 'SystemModule', 'DifferentScopeModule', 'CatalogSignedModule'
    }
}
}

# SIG # Begin signature block
# MIIFvwYJKoZIhvcNAQcCoIIFsDCCBawCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUGvhWPbSwHzC6imsIJvSv5v5q
# J0CgggNMMIIDSDCCAjCgAwIBAgIQTpO3RNGnQ6hFc1a6Iu66bTANBgkqhkiG9w0B
# AQsFADAoMSYwJAYDVQQDDB1QU0NhdGFsb2cgVGVzdCBSb290IEF1dGhvcml0eTAe
# Fw0xNjA4MTkwMDA1MDJaFw0xNzA4MTkwMDE1MDJaMCExHzAdBgNVBAMMFlBTQ2F0
# YWxvZyBDb2RlIFNpZ25pbmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDzDpS+berD3W9xRi0Poxhi1CKNFSom6yPoB9iKWeFJeiZOk4Tl5KZvyJdg0a/V
# Rj2ptlpLM8JpgXa++ce0JYPD7qRRHDEGqpbCZOTogu8kvydMVE5y3iSXIi5KYpVh
# 4Ofl7pI/e61KRGU7DTUMGVLatLOI7bBH0HnxFBR7HuTt5BUGWawSw4FGZVp/UiNT
# M1RTaj3HYIUar5GdznO3J1lyoT0aMDHHwmC+MJxwXdIZcE7XDRyTFZPAxCwNOpI4
# vvUxPBNA3S4HmUdYiA5gSmvvzf1d4QYB/QQbfiMFxzaQXs0PNofUyrbGTh3TteHI
# 1uhktqj2Gx+nwr3Nc7xqZD8dAgMBAAGjdTBzMA4GA1UdDwEB/wQEAwIBhjAMBgNV
# HRMBAf8EAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMB8GA1UdIwQYMBaAFKQulF/P
# jZ0Z9uOeoDCCdTGjf/wsMB0GA1UdDgQWBBSz3QAk9Tn3cJvAwGRR19qgUTb0lDAN
# BgkqhkiG9w0BAQsFAAOCAQEAAMLgDq51LxkTEk/ObH0DjVa1Vz24yVxQYYhP5fPW
# DR7aDBvWSkPlVG0RHQ+Vhnjuahu7tGs3ZWKUfruR7ZkBfNPwFbjYxLnwpGrzQPXO
# GaHOmH2B8UcRr2H9tnu/F6N/jsVX4sK+QdXdmUgLNan9LKeeabNHdLh7OMuNm56T
# yS6C+h1Oop7CWSHy/5D1o+OzGETqJQ6vZ/X8694RGGpJ9bDRfhB+DHnzbV02bG+O
# ZHCzhz+b/5R8WvTI9W4JA0AeAZZBCa5GMbK6LvqbsKKsEpMJirBRPDu8k6bsvthz
# 4AkTYQWki1U5nkDLPJzQbGb5jr0n96k9NS8QpVp5y/xZlzGCAd0wggHZAgEBMDww
# KDEmMCQGA1UEAwwdUFNDYXRhbG9nIFRlc3QgUm9vdCBBdXRob3JpdHkCEE6Tt0TR
# p0OoRXNWuiLuum0wCQYFKw4DAhoFAKB4MBgGCisGAQQBgjcCAQwxCjAIoAKAAKEC
# gAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwG
# CisGAQQBgjcCARUwIwYJKoZIhvcNAQkEMRYEFJ6LQ4vb7PDgx/cePy/OoO5l0xNl
# MA0GCSqGSIb3DQEBAQUABIIBADhuLKL34+tNDwVyt9/48r/huJziukwHvfB+a4sa
# 5Bjgn+CczeeC9KF8sW1fKT3XF0sWjyB5dpYHzuBGtqjMwru8jZwkHAV4TUfMYpe5
# hksaBIuFiMzA1cKh4sJhMS2XXSXZBNS57Zx4qx8tTC23yStJNMVCH+iB2cAvsIzL
# oeeGwQ6yrs+Rjge2UekZDCBT6MCtfseCXeXUl1fVTXoknfE6Q3APBVTfu/eFwV3i
# 6KNHht0S0qsrkA29OhU6P6O1yqbJJzSSt7jIj4rqC2owP3jY2KXMi15KmvfGtS4A
# tsEn+8Y7FM9y7mltNGXkWi7Z2E9/HJwqtWNx0kOGCyv+U4Q=
# SIG # End signature block
